name: Latest Blog Post Workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in personal website posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://zekeriyaay.com/feed.xml"
          max_post_count: "3"
          accept_header: "application/atom+xml"
          comment_tag_name: "BLOG-POST-LIST"
          committer_email: "zekeriya@zekeriyaay.com"
          committer_username: "Zekeriya AY"
          date_format: "UTC:mmm d, yyyy"
          template: "aaa$newline - [$randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ¨,ğŸ’š,ğŸ‘½ï¸,ğŸ’¡,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ‰,ğŸ’¥,ğŸ») $title]($url) &nbsp; *$date* <br> &nbsp; &nbsp; &nbsp; *$description*"
