name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in personal website posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://zekeriyaay.com/index.xml"
          max_post_count: "3"
          comment_tag_name: "BLOG-POST-LIST"
          committer_email: "zekeriya@zekeriyaay.com"
          committer_username: "Zekeriya AY"
          date_format: "UTC:mmm d, yyyy"
          template: "$newline - $date &nbsp; [$randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ‰,ğŸ’¥,ğŸ») $title]($url) &nbsp; &nbsp; $description"
      - name: Pull in youtube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCcg8zjG1kt-6sRfb4ajHWXQ"
          max_post_count: "5"
          comment_tag_name: "YOUTUBE-VIDEO-LIST"
          committer_email: "zekeriya@zekeriyaay.com"
          committer_username: "Zekeriya AY"
          template: "$newline - [$randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ‰,ğŸ’¥,ğŸ») $title]($url)"
